### ISSUE TITLE
Cannot make use of bundle functionality - Error appears

### ISSUE THREAD

**Issue by martinengelke** [buresdv/Cork#366]
# Bug Report

## Mandatory Information
**Describe the bug**
Cork is not able to produce a Brewfile with its included export functionality. 

**To Reproduce**
Run the export functionality.

**Expected Behavior**
Get a Brewfile with all my installed casks and packages as a backup solution.

**Screenshots**
<img width="617" alt="Bildschirmfoto 2024-07-20 um 09 11 45" src="https://github.com/user-attachments/assets/01900544-db10-4c93-af0b-350a09f30a79">

**System and Cork Information:**
 - macOS version: 14.5 (23F79)
 - Cork Version: 1.4.2 (62)
 - Did you compile Cork yourself?: No.

## Optional Information

**Additional context**
Nothing.

# Checklist
- [ x] I filled everything out under **Mandatory Information**
- [ ] This bug affects the UI and I have included a screenshot

**Comment by martinengelke** [comment]
Integrated terminal could help in those cases? Do I have to enable development functionality under options?

**Comment by buresdv** [comment]
I'm curious, what happens when you use the command `brew services list --json`?

**Comment by martinengelke** [comment]
Usage: brew services [subcommand]

Manage background services with macOS' launchctl(1) daemon manager or Linux's
systemctl(1) service manager.

If sudo is passed, operate on
/Library/LaunchDaemons//usr/lib/systemd/system  (started at boot).
Otherwise, operate on ~/Library/LaunchAgents/~/.config/systemd/user (started
at login).

[sudo] brew services [list] (--json) (--debug):
    List information about all managed services for the current user (or root).
Provides more output from Homebrew and launchctl(1) or systemctl(1) if run
with --debug.

[sudo] brew services info (formula|--all|--json):
    List all managed services for the current user (or root).

[sudo] brew services run (formula|--all):
    Run the service formula without registering to launch at login (or boot).

[sudo] brew services start (formula|--all|--file=):
    Start the service formula immediately and register it to launch at login
(or boot).

[sudo] brew services stop (formula|--all):
    Stop the service formula immediately and unregister it from launching at
login (or boot).

[sudo] brew services kill (formula|--all):
    Stop the service formula immediately but keep it registered to launch at
login (or boot).

[sudo] brew services restart (formula|--all):
    Stop (if necessary) and start the service formula immediately and register
it to launch at login (or boot).

[sudo] brew services cleanup:
    Remove all unused services.

      --file                       Use the service file from this location to
                                   start the service.
      --sudo-service-user          When run as root on macOS, run the service(s)
                                   as this user.
      --all                        Run subcommand on all services.
      --json                       Output as JSON.
      --no-wait                    Don't wait for stop to finish stopping the
                                   service.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --jsonn
(myenv) ***@***.*** sandkasten % brew services list --json 
Warning: No services available to control with `brew services`

**Comment by buresdv** [comment]
Did you use the command correctly? It should show you the list of services, and this appears when the command wasn't recognized. Can you try again?

**Comment by buresdv** [comment]
Closed due to inactivity

**Comment by martinengelke** [comment]
Hi David,

sorry I was not at home. 

I tried again _brew services list --json_ and even _sudo brew services list --json_ 

and that's what I get:

Warning: No services available to control with `brew services`

If I type:

_brew services debug_

I get:

> /opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pyenv
> /opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ant
> /opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pkg-config
> /opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libtiff
> /opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/xorgproto
> /opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxau
> ...

**Comment by buresdv** [comment]
Hey, no problem. Thank you for getting back.

Can you please try exporting a backup on the branch `transferable.brewfile-fixes`? There is some additional debugging.

The export will fail, but you will get a much more detailed output. For example:
```
Output of brewfile dumping: , /usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libtiff
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libtool
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libidn2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/thefuck
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/little-cms2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gh
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/vapor
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading tuist/tuist/tuist@4.21.2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/nettle
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pixman
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gdbm
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libuv
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/argon2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/rtmpdump
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/imath
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libavif
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gts
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libunistring
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pango
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/highway
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libyaml
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openjdk@11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/apr-util
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/brotli
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gdk-pixbuf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/icu4c
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/harfbuzz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/python@3.12
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/glib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/netpbm
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/aom
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ruby-install
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/graphite2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/wireguard-go
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/cairo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/webp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libgpg-error
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/c-ares
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/fribidi
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/php
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/unixodbc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libnghttp2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/bash
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openexr
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/fontconfig
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/chruby
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openjdk
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/curl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/giflib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/krb5
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxrender
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libuninameslist
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/freetds
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libvmaf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libssh2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/bazel
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/librsvg
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/graphviz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/swiftformat
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libsodium
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/dav1d
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/apr
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/autoconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libpq
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/aspell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/tidy-html5
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/m4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/oniguruma
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/woff2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/unshield
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/jpeg-xl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libspiro
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/node
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libzip
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/wireguard-tools
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openldap
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/fontforge
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/jasper
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/bison
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/fswatch
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/automake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lzo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libffi
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/jpeg-turbo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading tuist
Error: Failure while executing; `brew services list` exited with 127. Here's the output:
/opt/homebrew/Library/Homebrew/utils/popen.rb:12:in `popen_read'
/opt/homebrew/Library/Homebrew/utils/popen.rb:16:in `safe_popen_read'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_services.rb:41:in `started_services'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_services.rb:35:in `started?'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:68:in `block in dump'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:58:in `map'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:58:in `dump'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:22:in `build_brewfile'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:35:in `dump_brewfile'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:11:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:138:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Can you post your output? It's the last message that starts with `Output of brewfile dumping`

**Comment by martinengelke** [comment]
Hi,

I actually don’t know what to type into the terminal to get the output shown.

What do you mean by: "a backup on the branch transferable.brewfile-fixes“?

I tried 

brew bundle dump -d

Since brew bundle is just working fine and delivering a brewfile.

**Comment by buresdv** [comment]
What I mean is:

1. Download and compile the code on the branch named `transferable.brewfile-fixes`
2. Inside that version of Cork, try creating a backup

That will show you the debug output in Xcode's terminal, which you should copy here

**Comment by martinengelke** [comment]
Sorry, 
Maybe you can provide me a link? I cannot find any branch with the given name.


> Am 12.08.2024 um 15:42 schrieb David Bureš ***@***.***>:
> 
> transferable.brewfile-fixes

**Comment by martinengelke** [comment]
phew :) 
I don't have Xcode installed.

**Comment by buresdv** [comment]
I did a clean reinstall of Homebrew and I'm no longer getting this error. Maybe it's another of those things

**Comment by martinengelke** [comment]
Hi, are you back from china? :)

I am currently not able to play around with reinstalling homebrew but if I get to this point (since I indeed try to manage my dot files more efficient beside my work) I will let you know.

**Comment by abraver** [comment]
I'm having the same issue: File > Export Homebrew Backup... leads to an error message "Couldn't write Homebrew backup.  Error: Failure while executing; `brew services list` exited with 127. Here's the output:"  (There is nothing displayed for the output).

`brew services list --json` runs fine in the terminal with no issues.

Has anyone resolved this issue?

**Comment by buresdv** [comment]
This bug is *still* caused by Homebrew freaking out if there are services installed - and I still can't to anything about it :(

**Comment by buresdv** [comment]
Fixed for me as well on the latest `2.0.0` Beta 3
